config/routes.rb
Rails.application.routes.draw do

  root to:'impressions#new'

  resources :impressions, only: [:show, :new, :create, :edit, :update]
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create]

end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  link       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Artist < ActiveRecord::Base
  validates :name, presence: true

  has_many :works
end

app/models/impression.rb
# == Schema Information
#
# Table name: impressions
#
#  id                 :integer          not null, primary key
#  user_id            :integer          not null
#  work_id            :integer          not null
#  reflection         :text
#  spoiler_reflection :text
#  started_at         :datetime
#  finished_at        :datetime
#  created_at         :datetime
#  updated_at         :datetime
#

class Impression < ActiveRecord::Base

  belongs_to :user
  belongs_to :work

  validates :user, :work, presence: true

  delegate :title, to: :work
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id            :integer          not null, primary key
#  impression_id :integer          not null
#  body          :text
#  is_spoiler    :boolean          default(FALSE)
#  created_at    :datetime
#  updated_at    :datetime
#

class Note < ActiveRecord::Base

  belongs_to :impression
  has_one :user, through: :impression
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  username      :string(255)      not null
#  password_hash :string(255)      not null
#  session_token :string(255)      not null
#  created_at    :datetime
#  updated_at    :datetime
#

class User < ActiveRecord::Base
  has_many :impressions
  has_many :notes, through: :impressions

  attr_reader :password

  validates_uniqueness_of :username, :session_token
  validates_presence_of :username, :session_token
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  def password=(password)
    @password=password
    self.password_hash = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_hash).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= generate_token
  end

  def generate_token
    SecureRandom::urlsafe_base64(16)
  end

end

app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  artist_id  :integer
#  medium     :string(255)
#  link       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Work < ActiveRecord::Base

  validates :title, presence: true
  belongs_to :artist
  has_many :impressions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    current_user != nil
  end

  def sign_in!(user)
    session[:token] = user.reset_session_token!
  end

  def sign_out!
    current_user.try(:reset_session_token)
    @current_user = nil
    session[:token] = nil
  end

  helper_method :signed_in?

end

app/controllers/impressions_controller.rb
class ImpressionsController < ApplicationController

  def index

  end

  def show
    @impression = Impression.find(params[:id])
  end

  def new
    @impression = Impression.new
  end

  def create
    @impression = current_user.impressions.new(impression_params)
    Impression.transaction do
      @impression.work = Work.find_or_create_by(
          title: params[:impression][:title],
          artist: Artist.find_or_create_by(name: params[:impression][:artist])
      )
      # debugger
      if @impression.save
        flash[:success] = "Huzzah!"
        redirect_to @impression
      else
        flash.now[:errors] = @impression.errors.full_messages
        render :new
      end
    end
  end

  private

  def impression_params
    params.require(:impression).permit([:reflection, :spoiler_reflection, :started_at, :finished_at])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    @user = User.find_by_username(params[:username])
    if @user.is_password? params[:password]
      sign_in! @user
      redirect_to @user
    else
      flash.now[:error] = "Incorrect username or password."
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in!(@user)
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit([:username, :password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/impressions_helper.rb
module ImpressionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/impressions/new.slim
form.impression-form action=impressions_url method="POST"
  input type="hidden" value=form_authenticity_token name="authenticity_token"
  input.form-control type="text" name="impression[title]" placeholder="title" value=@impression.work.try(:title)
  input.form-control type="text" name="impression[artist]" placeholder="artist"
  input.form-control.date type="date" name="impression[finish_date]"
  textarea.form-control name="impression[reflection]" placeholder="so..."
  textarea.form-control name="impression[spoiler_reflection]" placeholder="(spoilers)"
  input.form-control type="submit"

app/views/impressions/show.slim
h1 = @impression.title
p = @impression.reflection
p = @impression.spoiler_reflection

app/views/layouts/_navbar.slim
nav.navbar role='navigation'
  .container-fluid
    .navbar-header
      = link_to 'Aquarium', root_url, class: 'navbar-brand'
    ul.nav.navbar-nav
      - if signed_in?
        li = link_to 'New', new_impression_url
      - else
        li = link_to 'Sign in', new_session_url
        li = link_to 'Sign up', new_user_url

app/views/layouts/application.slim
doctype html
html
  head
    title Aquarium
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body class="#{controller_name} #{action_name}"
    = render partial: 'layouts/navbar'
    - if flash[:success]
      .success= flash[:success]
    - if flash[:errors]
      ul
        - flash[:errors].each do |message|
          li= message
    .content
      = yield

app/views/users/new.slim
= form_for @user do |f|
  = f.text_field :username
  = f.password_field :password
  = f.submit value: 'Sign up'

app/views/users/show.slim
h1 = @user.username